### ISSUE TITLE
Generate separate zip files  per theme

### ISSUE THREAD

**Issue by Sacro** [catppuccin/cursors#10]
I'm trying to put my home folder into a dotfiles repo using [chezmoi](https://www.chezmoi.io/) however it doesn't easily support pulling an external file in, and then extracting a file contained inside it.

Is it possible to have all the themes in individual files so I can pull just what I need?

**Comment by nekowinston** [comment]
I'm confused what you're requesting here, as the Releases already offer each Flavor-Accent combination: https://github.com/catppuccin/cursors/releases/tag/v0.2.0

**Comment by Sacro** [comment]
Ignore me then, I was pulling main, but I don't need to.

**Comment by nekowinston** [comment]
As a final note, if you're using `.chezmoiexternal`, you can specify [`include`](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-with-selected-files-from-a-url), to include only selected files from an archive URL.

**Comment by Sacro** [comment]
Or you can I'
Use `archive-file` for similar features.
