### ISSUE TITLE
Ambiguous Instructions

### ISSUE THREAD

**Issue by VehementHam** [catppuccin/cursors#12]
The instructions are to "Choose a theme in the Settings". Please change this to instructions that work for all users rather than just desktop environment users.

**Comment by elkrien** [comment]
It's not possible to satisfy all desktop and windows managers users. "Choose a theme in the Settings" is an universal phrase to all kinds of desktop environments - just the Settings are in different place in Gnome, KDE, Qtile, DWM, i3 etc.
