### ISSUE TITLE
Mouse wheel cursor support

### ISSUE THREAD

**Issue by TheElegantCoding** [catppuccin/cursors#14]
Maybe this is not possible and i'm very surprised but a lot of cursors themes don't support this icon

![image](https://github.com/catppuccin/cursors/assets/70770072/0c6a984c-41e9-4934-abff-3a14c6c7e9d2)

when you press the middle or scroll wheel of the mouse you can see this cursor, but i don't know how to modified

**Comment by CommanderGL** [comment]
Correct me if I'm wrong, but isn't that for windows only as this is a linux cursor theme.

**Comment by TheElegantCoding** [comment]
it's for windows, i actually found windows don't support change all the icons of the cursor, only some of them

**Comment by CommanderGL** [comment]
Well then shouldn't you close the issue as this repo is linux only.
