### ISSUE TITLE
why it doesn't work in firefox or some certain applications, it still is adwaita?

### ISSUE THREAD

**Issue by fhawk12** [catppuccin/cursors#15]
I am a newbie for linux, I install it by `yay -S catppuccin-cursors-mocha ` command, that is my config content in file `/usr/share/icons/default/index.theme`
```
[Icon Theme]
Inherits=Catppuccin-Mocha-Light-Cursors
```
my desktop is hyprland.
In some other application it works, I don't know why just like firefox, waybar, clash-verge etc, it doesn't work and automatically swtich to adwaita.

**Comment by CommanderGL** [comment]
does it work on any other apps and how did you install firefox (with pacman, yay, or flatpak)

**Comment by fhawk12** [comment]
I install firefox with pacman, and it works with some apps, but some not. that is why I am confused.

**Comment by CommanderGL** [comment]
Try putting this in your `hyprland.conf`:
```
env = HYPRCURSOR_THEME,Catppuccin-Mocha-Light-Cursors
env = HYPRCURSOR_SIZE,16
env = XCURSOR_THEME,Catppuccin-Mocha-Light-Cursors
env = XCURSOR_SIZE,16
exec-once = hyprctl setcursor Catppuccin-Mocha-Light-Cursors 16
```
