### ISSUE TITLE
Add Hyprcursor support

### ISSUE THREAD

**Issue by nonetrix** [catppuccin/cursors#17]
Hyprcursor is an SVG-based cursor format used in Hyprland, intended to replace xcursor. It offers numerous benefits, including a smaller file size and the use of SVG. For example, this should allow the cursor to expand when shaken, similar to macOS, without appearing pixelated

Repo here: https://github.com/hyprwm/hyprcursor

**Comment by CommanderGL** [comment]
Please!!!!!

**Comment by trowgundam** [comment]
I have implemented this and submitted a PR, #18. I've tested this on my own machine running Hyprland on Arch, and everything appears to be working wonderfully. Feel free to pull my fork and build the cursors for yourself until (hopefully) my PR is merged.
