### ISSUE TITLE
Recommendation: Windows Cursors

### ISSUE THREAD

**Issue by muffinV136** [catppuccin/cursors#2]

**Comment by Anxiemon** [comment]
agreed. was eager to use 'em but the .theme file doesn't work lol

**Comment by ItsProfessional** [comment]
Unofficial: https://www.deviantart.com/niivu/art/Catppuccin-Cursors-921387705

**Comment by Anxiemon** [comment]
> Unofficial: https://www.deviantart.com/niivu/art/Catppuccin-Cursors-921387705 It has the same look as the cursors in this repo

Still, it's incomplete, as there only are Latte and Mocha cursors.

**Comment by Anxiemon** [comment]
> Unofficial: https://www.deviantart.com/niivu/art/Catppuccin-Cursors-921387705 It has the same look as the cursors in this repo

also you can't download it

**Comment by ItsProfessional** [comment]
> > Unofficial: https://www.deviantart.com/niivu/art/Catppuccin-Cursors-921387705 It has the same look as the cursors in this repo
> 
> also you can't download it

https://github.com/niivu/windows-customization-extras/raw/main/Cursors/Catppuccin%20Cursors%20for%20Windows%20by%20niivu.zip

**Comment by muffinV136** [comment]
I think I should close this now, as is pretty much irrelevant. Plus I might up be switching to Linux Mint as a secondary daily driver.

**Comment by isabelincorp** [comment]
I'm changing this to not planned, since it isn't _really_ completed. Niivu's cursor theme isn't complete as it doesn't have frappe/macchiato, nor different sizes.
