### ISSUE TITLE
Split packages for nix

### ISSUE THREAD

**Issue by Arjun31415** [catppuccin/cursors#28]
The current nix implementation builds all accents and all flavors. It would be nice to have an option to build only the required cursor and optionally support hyprcursor.

**Comment by isabelroses** [comment]
The current nix package only builds zips too, but thats on purpose its not for public consumption but rather to get a consistant CI build since hyprcursor was already packaged for nixpkgs. If you want to use catppuccin-cursors please use the upstream package instead.
