### ISSUE TITLE
Cursor becoming an X when right-clicking in certain applications

### ISSUE THREAD

**Issue by dr460nf1r3** [catppuccin/cursors#32]
Hi :) 

Thanks for those fancy cursors! I'm having a strange issue where the cursor shortly becomes an X when right-clicking in certain applications. I think a short video explains it best:

[Screencast_20240804_153832.webm](https://github.com/user-attachments/assets/6c176356-f37c-48ac-af9d-3dd3d05efe63)

This only happens in some applications, e.g. on Chromium. For other ones (e.g. KDE applications, Qt applications in general, it works as expected). 

Further information:
- OS: NixOS
- DE: KDE (Wayland)
- (In case Nix folks read this: [this](https://gitlab.com/garuda-linux/garuda-nix-subsystem/-/blob/main/internal/modules/catppuccin/dotfiles.nix?ref_type=heads#L70) is the particular config from the Catppuccin Nix flake in use)

Thanks!

**Comment by isabelroses** [comment]
My best guess for the chromium one is that chromium is running under X, try launch it with these flags (which force it to run in wayland mode) to see if the issue persists `--ozone-platform=wayland --enable-features=UseOzonePlatform`. If it does then its likely a X cursors issue.

**Comment by dr460nf1r3** [comment]
> If it does then its likely a X cursors issue.

Did as outlined and it does in fact cause the glitch to no longer appear. It is highly likely that the other applications were suffering the same fate then. Thanks! I didn't even realize Chromium wasn't running on Wayland until now.
