### ISSUE TITLE
dconf/dconf-editor cannot change size of cursor beyond 32 for gtk apps

### ISSUE THREAD

**Issue by garare992** [catppuccin/cursors#33]
Using nixos and hyprland. 

For GTK applications I have to use dconf, per this article. https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/

I tried to change the cursor-size via both command-line (dconf) and gui (dconf-editor) app.

dconf write /org/gnome/desktop/interface/cursor-size "16"
dconf write /org/gnome/desktop/interface/cursor-size "24"
dconf write /org/gnome/desktop/interface/cursor-size "32"

All change the cursor like how you would expect. 

But the cursor stays at size 32 for the following:

dconf write /org/gnome/desktop/interface/cursor-size "48"
dconf write /org/gnome/desktop/interface/cursor-size "64"
dconf write /org/gnome/desktop/interface/cursor-size "96"

Same results if you do it with dconf-editor.

**Comment by sgoudham** [comment]
Hey :wave:,

I know you're on Hyprland but we just released [v1.0.0](https://github.com/catppuccin/cursors/releases/tag/v1.0.0) which should fix the scaling for GNOME, could you please try the assets from that release and let me know if that fixes your issue? 

Thanks!

**Comment by sgoudham** [comment]
Going to close this as resolved as the author hasn't responded. 
Feel free to re-open if you're still running into your issue on the latest release!
