### ISSUE TITLE
XCURSOR_THEME does not recognise cursor from theme name in `~/.icons` and `~/.local/share/icons`

### ISSUE THREAD

**Issue by garare992** [catppuccin/cursors#34]
Nixos home-manager uses wrong cursor name in ~/.icons and ~/.local/share/icons.

this is what i have in my home.nix:

home.pointerCursor = {
name = "catppuccin-cursors-latteRed";
package = pkgs.catppuccin-cursors.latteRed;
};

To get the real cursor name that XCURSOR_THEME will recognize, I have to do this:

```
>ls -l
catppuccin-cursors-latteRed -> /nix/store/a958i8b43fmk1sgn6d91by1ib20gx2i6-home-manager-files/.local/share/icons/catppuccin-cursors-latteRed
>cd  /nix/store/a958i8b43fmk1sgn6d91by1ib20gx2i6-home-manager-files/.local/share/icons/
>ls -l
catppuccin-cursors-latteRed -> /nix/store/z19x7n2qqh9z9r08i8aabpi15vnfm6im-catppuccin-cursors-0.3.0-latteRed/share/icons/catppuccin-cursors-latteRed
>cd /nix/store/z19x7n2qqh9z9r08i8aabpi15vnfm6im-catppuccin-cursors-0.3.0-latteRed/share/icons/
>ls
catppuccin-latte-red-cursors
> cp -r catppuccin-latte-red-cursors ~/.local/share/icons
```

then change XCURSOR_THEME to catppuccin-latte-red-cursors

**Comment by isabelroses** [comment]
Your `name` should be this instead `catppuccin-cursors-latte-red` and it should just work.
```nix
home.pointerCursor = {
name = "catppuccin-cursors-latte-red";
package = pkgs.catppuccin-cursors.latteRed;
};
```

**Comment by garare992** [comment]
> Your `name` should be this instead `catppuccin-cursors-latte-red` and it should just work (seeing as theres not issues from catppuccin/nix).
> 
> ```nix
> home.pointerCursor = {
>   name = "catppuccin-cursors-latte-red";
>   package = pkgs.catppuccin-cursors.latteRed;
> };
> ```

That doesn't work

**Comment by isabelroses** [comment]
Sorry I miss read it, it's supposed to be `catppuccin-latte-red-cursors`

**Comment by garare992** [comment]
> Sorry I miss read it, it's supposed to be `catppuccin-latte-red-cursors`

But that means you first have to install Catppuccin with a temporary name, follow all the symlinks to find the real name, and then return to the Home Manager configuration to update the temporary name to the correct one. Isn't the purpose of the name variable to avoid this hassle and allow you to specify the folder's name from the start?

**Comment by isabelroses** [comment]
> > Sorry I miss read it, it's supposed to be `catppuccin-latte-red-cursors`
> 
> But that means you first have to install Catppuccin with a temporary name, follow all the symlinks to find the real name, and then return to the Home Manager configuration to update the temporary name to the correct one. Isn't the purpose of the name variable to avoid this hassle and allow you to specify the folder's name from the start?

Yes that is the point, the issue was that i misread from here https://github.com/catppuccin/nix/blob/66f4ea170093b62f319f41cebd2337a51b225c5a/modules/home-manager/cursor.nix#L32

**Comment by sgoudham** [comment]
Am I right in saying that this issue can be closed now? Little bit unsure from the prior conversation and I don't believe it's relevant to this repository?

**Comment by isabelroses** [comment]
> Am I right in saying that this issue can be closed now? Little bit unsure from the prior conversation and I don't believe it's relevant to this repository?

I think it should be good to close. The issue was with user configuration not the theme.
