### ISSUE TITLE
hyprcursors don't scale higher than 24.

### ISSUE THREAD

**Issue by aljustiet** [catppuccin/cursors#36]
When I change the cursor size using the `hyprctl setcursor catppuccin-frappe-sapphire 32`, it doesn't apply. Here's the [demo](https://files.catbox.moe/44v4ve.mp4).x
Version: 0.3.1
Package [source](https://aur.archlinux.org/packages/catppuccin-cursors-frappe)

**Comment by sgoudham** [comment]
Closing as this is effectively a duplicate of #31
