### ISSUE TITLE
[Question] Arch package on aur

### ISSUE THREAD

**Issue by jorgebodega** [catppuccin/cursors#4]
Hello!

I'm trying to migrate to catppuccin from Nord theme, and I'm really comfortable with this flavours!

Do you have any plans to automate deploys with releases or commits? I use arch and would be great to install this packages automatically instead of manually upgrade version.

I can try to help with this, if this is intended.

Regards!

**Comment by ghostx31** [comment]
Sure. I can write up a GH actions script to build zips for the cursors. I can also write an AUR package for the cursors since I already maintain the AUR GTK packages as well.

**Comment by jorgebodega** [comment]
Nice! I'm having this trouble with almost every package, but I know there are too many. If you are going to work on this, and need any help, please mention me

**Comment by ghostx31** [comment]
AUR packaging does not work that way. There are no `assets` stored in the AUR, just the `PKGBUILD`s. The downloading of the built zips and other stuff is done via `makepkg` itself which it reads from the `PKGBUILD`.

**Comment by jorgebodega** [comment]
I know, I know. I mean, there are no upgrade of aur version whenever a release is done.

**Comment by ghostx31** [comment]
Oh yeah I manually update the `PKGBUILD` for the GTK packages since there is no clear way to automate this with github actions because AUR requires my private ssh key.

**Comment by jorgebodega** [comment]
Really nice man! Thx for your work ❤️
