### ISSUE TITLE
Incorrect offset on hand

### ISSUE THREAD

**Issue by Optimoos** [catppuccin/cursors#46]
Since the update to 1.0, I've noticed that the pointing hand cursor (the one that comes up when hovering a link) seems to be incorrectly offset. The pointing location appears to be in the palm instead of at the end of the finger. I've only tested this with macchiato, but it's happening with multiple colors and sizes. Everything works as expected with the default theme.

I'm on Arch, installed from AUR.

**Comment by Blatant22** [comment]
Can confirm this, also on Arch using `catppuccin-cursors-macchiato` from the AUR. Required to focus selections via the thumb instead of the index finger.

**Comment by Cofeiini** [comment]
I have the same issue with `catppuccin-cursors-mocha`, but modifying the "hotspot_y" value in `/usr/share/icons/catppuccin-mocha-dark-cursors/cursors_scalable/pointer/metadata.json` (or where the cursor themes are installed) and reloading the theme seems to fix this. I tried with 7.0 and it worked pretty well.

Manually editing the metadata is a temporary solution though.

**Comment by jinliu** [comment]
You can remove `display="none"` in "cursor_scalable/*.svg" and do a visual check on hotspots.

Here's my check results (haven't checked all):
1. alt-scroll => 15.5, 15.5
2. bottom-left-corner => 6.0, 26.0
3. bottom-right-corner => 7.0, 26.0
4. bottom_size => 16.0, 21.5

Please note that the top-left corner of the "hotspot" rectangle is used as the hotspot, not its center.

**Comment by sgoudham** [comment]
I won't be able to test https://github.com/catppuccin/cursors/pull/47 until the weekend.

I'd appreciate if someone else could confirm if the PR fixes all the hotspot values.
