### ISSUE TITLE
latteLight is dark

### ISSUE THREAD

**Issue by elbaro** [catppuccin/cursors#59]
Unlike the preview, the nixpkg `pkgs.catppuccin-cursors.latteLight` has dark fililngs.

/nix/store/j72vyl66q5larrlx697bvpg7xjjmq0ah-catppuccin-cursors-1.0.1-latteLight/share/icons/catppuccin-latte-light-cursors/cursors_scalable/default/default.svg

![image](https://github.com/user-attachments/assets/8df7ddff-290e-4382-ac5c-1de8c4928583)

**Comment by sgoudham** [comment]
> Do you know what was used to make them?

This repository predates me but I'm guessing all the SVGs were imported into an image editor, aligned into rows and then into a catwalk preview.
