### ISSUE TITLE
HiDPI version

### ISSUE THREAD

**Issue by ooonea** [catppuccin/cursors#9]
I suggest a HiDPI version of the sliders. On my laptop, they look really tiny. A Bibata-type size would be needed.

**Comment by sgoudham** [comment]
Hey :wave:,

We've just released [v1.0.0](https://github.com/catppuccin/cursors/releases/tag/v1.0.0) which provides cursor sizes from 16px all the way up to 96px. I believe this should resolve any issues you have with cursor size as they should scale properly.

Closing this now but feel free to re-open if you're unable to get the new release assets working for you!
